### PR TITLE
fix NGen issue

### PR DESCRIPTION
**Pull request by Jinhuafei**

### CODE REVIEW

**Comment by pharring** [comment]
Can you give more detail?
I saw a corresponding change already in the microsoft/dotnet-framework:4.7.1 Dockerfile:
https://github.com/Microsoft/dotnet-framework-docker/pull/28

Assuming we pick up the latest with that fix, is it actually necessary to do it again here?

**Comment by richlander** [comment]
The env variable should be inherited.

**Comment by pharring** [comment]
@richlander Not just the env variable, but is it necessary to run 'ngen update' again?

**Comment by pharring** [comment]
@richlander As we noted in #57, the environment variable isn't inherited since it's not in an ENV statement.
I question is whether we need to re-do the "ngen update" before ngen-ing Roslyn. I suspect not.

**Pull request merged**
