### PR TITLE
Add Windows 1709-based 4.7.1 image

### PR DESCRIPTION
**Pull request by richlander**
Based on https://github.com/Microsoft/dotnet-framework-docker/pull/31

### CODE REVIEW

**Comment by pharring** [comment]
@shirhatti I believe the answer is no, we don't need it. As discussed in #56, that environment variable is already set in the base image.

**Comment by shirhatti** [comment]
@pharring The base image you've linked to is an RS1 base image. I'm not sure it's baked into the RS3 base image

**Comment by pharring** [comment]
Oh, maybe you're right, but it's subtle. See here:
https://github.com/Microsoft/dotnet-framework-docker/blob/master/4.7.1-windowsservercore-1709/Dockerfile
The COMPLUS_... environment variable is set in the RUN statement, but there's no ENV statement, so it is NOT inherited.

I guess the question to @richlander is whether we need to set that COMPLUS environment variable in order to ngen the Roslyn compiler binaries.

**Comment by shirhatti** [comment]
Good catch. I clearly missed that.
It'd be nice if we can do it the same way across both the images for the sake of consistency.

**Pull request merged**
