### PR TITLE
Add note about WinNAT

### PR DESCRIPTION
**Pull request by shirhatti**

### CODE REVIEW

**Comment by shirhatti** [comment]
@BillWagner I borrowed language from your article to make the readme more comprehensive. Can I merge these changes?

**Comment by BillWagner** [comment]
@shirhatti We have a pull request that suggests using docker inspect instead:

https://github.com/dotnet/core-docs/pull/1108

I think it would be best to add that, with the notes that @spboyer suggested.

**Comment by shirhatti** [comment]
@BillWagner Made the requested change

**Comment by BillWagner** [comment]
@shirhatti I should have referenced this PR https://github.com/dotnet/core-docs/pull/1107

See @spboyer comments to include both.

**Pull request merged**
